name: Cryptosoft-SBOM-DT
description: This action builds a CycloneDX Format Software Bill of Materials (SBOM) for a repository and sends it to an OWASP DT server.

inputs:
  dt-url:
    description: 'The URL of the Dependency-Track API server to send the SBOM.'
    required: true
  api-key:
    description: 'The API key used to authenticate with the Dependency-Track API server.'
    required: true
  project-name:
    description: 'Project name.'
    required: true
  project-version:
    description: 'Project version.'
    required: true
  parent-name:
    description: 'Parent Project name.'
    required: false  # Parent project is optional
  parent-version:
    description: 'Parent Project Version.'
    required: false  # Parent project version is optional

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Generate SBOM
      id: sbom
      uses: AppThreat/cdxgen-action@v1
      with:
        output: "./reports/bom.xml"  # Updated output path

    - name: Verify SBOM File  # Ensures SBOM was created
      run: |
        if [ -f "./reports/bom.xml" ]; then
          echo "SBOM file generated successfully!"
          ls -lah ./reports/bom.xml
          cat ./reports/bom.xml
        else
          echo "SBOM file was NOT generated!" && exit 1
        fi
      shell: bash

    - name: Upload SBOM to OWASP Dependency-Track
      run: |
        if [[ -n "${{ inputs.parent-name }}" && -n "${{ inputs.parent-version }}" ]]; then
          curl -k -X POST "${{ inputs.dt-url }}/api/v1/bom" \
            -H "Content-Type: multipart/form-data" \
            -H "X-Api-Key: ${{ inputs.api-key }}" \
            -F "autoCreate=true" \
            -F "projectName=${{ inputs.project-name }}" \
            -F "projectVersion=${{ inputs.project-version }}" \
            -F "parentName=${{ inputs.parent-name }}" \
            -F "parentVersion=${{ inputs.parent-version }}" \
            -F "bom=@./reports/bom.xml"
        else
          curl -k -X POST "${{ inputs.dt-url }}/api/v1/bom" \
            -H "Content-Type: multipart/form-data" \
            -H "X-Api-Key: ${{ inputs.api-key }}" \
            -F "autoCreate=true" \
            -F "projectName=${{ inputs.project-name }}" \
            -F "projectVersion=${{ inputs.project-version }}" \
            -F "bom=@./reports/bom.xml"
        fi
      shell: bash
