name: Cryptosoft-SBOM-DT
description: This action builds a CycloneDX Format Software Bill of Materials (SBOM) for a repository and sends it to a OWASP DT server
inputs:
  dt-url:
    description: 'The URL of the Dependency-Track API server to send the SBOM to OWASP Dependency Track Server'
    required: true
  api-key:
    description: 'The API key used to authenticate with the Dependency-Track API server.'
    required: true
  project-name:
    description: 'Project name.'
    required: true
  project-version:
    description: 'Project version.'
    required: true
  parent-name:
    description: 'Parent Project name.'
    required: true
  parent-version:
    description: 'Parent Project Version.'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - id: sbom
      uses: AppThreat/cdxgen-action@v1
      with:
        output: './reports/bom.xml'
    - id: saveBom
      run: |
        echo -n "$(cat './reports/bom.xml')" > sbom.xml
      shell: bash
    - run: |
          if [[ -n "${{ inputs.parent-name }}" && -n "${{ inputs.parent-version }}" ]]; then
          curl -k -X POST "${{ inputs.dt-url }}/api/v1/bom" \
            -H "Content-Type: multipart/form-data" \
            -H "X-Api-Key:${{ inputs.api-key }}" \
            -F "autoCreate=true" \
            -F "projectName=${{ inputs.project-name}}" \
            -F "projectVersion=${{ inputs.project-version}}" \
            -F "parentName=${{ inputs.parent-name}}" \
            -F "parentVersion=${{ inputs.parent-version}}" \
            -F "bom=@sbom.xml"
          else
          curl -k -X POST "${{ inputs.dt-url }}/api/v1/bom" \
            -H "Content-Type: multipart/form-data" \
            -H "X-Api-Key:${{ inputs.api-key }}" \
            -F "autoCreate=true" \
            -F "projectName=${{ inputs.project-name}}" \
            -F "projectVersion=${{ inputs.project-version }}" \
            -F "bom=@sbom.xml"
          fi     
      shell: bash
